### ISSUE TITLE
Could you add a checksum?

### ISSUE THREAD

**Issue by 030** [ozankasikci/dockerfile-generator#1]
I prefer to check a checksum to ensure that I downloaded the correct binary.

**Comment by ozankasikci** [comment]
Checksums added:

https://github.com/ozankasikci/dockerfile-generator/releases/tag/v0.0.1

**Comment by ozankasikci** [comment]
@030 Could you please close the issue after confirming that the checksums are valid?

**Comment by 030** [comment]
@ozankasikci Ok I will check now. Perhaps you could updated the README as well, e.g.:

```

> curl -L https://github.com/030/n3dr/releases/download/3.1.1/n3dr-linux -o n3dr-linux
> curl -L https://github.com/030/n3dr/releases/download/3.1.1/n3dr-linux.sha512.txt -o n3dr-linux.sha512.txt
> sha512sum --check n3dr-linux.sha512.txt
> chmod +x n3dr-linux
> ./n3dr-linux

```

**Comment by 030** [comment]
**Test**

Local

sha512sum /usr/local/bin/dfg 
481a37b673c7b2ab82c16a631a6b5c6c2d1770b223dbe89b267e99b377c2cc5652b37fc270cfc49f8b67c8a4c59badbbdfecf0ce5935e16f51631979e490d14a  /usr/local/bin/dfg

**According to github**



**Outcome**

match
